"""
Resume bullet post-processing and validation.

This module provides functions to clean, validate, and verify resume bullets
generated by the AI agent, ensuring they are grounded in actual repository data.
"""

import re
from typing import Any


def clean_bullets(raw_text: str) -> list[str]:
    """
    Clean and normalize resume bullets from raw AI-generated text.

    This function:
    1. Extracts individual bullet points from markdown/text
    2. Removes conversational filler and AI chatter
    3. Deduplicates identical bullets
    4. Enforces strict length limits per bullet
    5. Normalizes formatting and whitespace

    Args:
        raw_text: Raw text output from the AI agent, potentially containing
                  conversational prefixes, markdown formatting, and multiple bullets

    Returns:
        List of clean, deduplicated bullet strings ready for resume display

    Example:
        >>> raw = '''Here are your bullets:
        ... • Built FastAPI application
        ... • Built FastAPI application
        ... • Implemented React frontend
        ...
        ... Let me know if you need more!'''
        >>> clean_bullets(raw)
        ['Built FastAPI application', 'Implemented React frontend']
    """
    # Maximum characters per bullet (typical resume standard)
    MAX_BULLET_LENGTH = 200

    # Common conversational prefixes to strip
    CONVERSATIONAL_PATTERNS = [
        r"^here\s+(are|is)\s+(your|the)\s+bullets?:?\s*",
        r"^i'?ve\s+generated\s+the\s+following:?\s*",
        r"^based\s+on\s+.*?:?\s*",
        r"^let\s+me\s+know\s+.*$",
        r"^feel\s+free\s+.*$",
        r"^hope\s+this\s+helps.*$",
        r"^is\s+there\s+anything.*$",
        r"^would\s+you\s+like.*$",
    ]

    # Step 1: Remove conversational filler using patterns
    cleaned_text = raw_text
    for pattern in CONVERSATIONAL_PATTERNS:
        cleaned_text = re.sub(pattern, "", cleaned_text, flags=re.IGNORECASE | re.MULTILINE)

    # Step 2: Extract bullet points
    # Look for lines starting with bullet markers (•, -, *, or numbered lists)
    bullet_patterns = [
        r"^[•\-\*]\s+(.+)$",  # Markdown bullets: •, -, *
        r"^\d+[\.\)]\s+(.+)$",  # Numbered lists: 1. or 1)
    ]

    bullets: list[str] = []

    for line in cleaned_text.split("\n"):
        line = line.strip()

        # Skip empty lines
        if not line:
            continue

        # Try to match bullet patterns
        matched = False
        for pattern in bullet_patterns:
            match = re.match(pattern, line)
            if match:
                bullet_text = match.group(1).strip()
                bullets.append(bullet_text)
                matched = True
                break

        # If no bullet marker found but line looks substantial, include it
        # (handles cases where AI returns plain text without markers)
        if not matched and len(line) > 20 and not any(
            re.search(p, line, re.IGNORECASE) for p in CONVERSATIONAL_PATTERNS
        ):
            bullets.append(line)

    # Step 3: Clean each bullet
    cleaned_bullets = []
    for bullet in bullets:
        # Remove extra whitespace
        bullet = " ".join(bullet.split())

        # Remove trailing punctuation artifacts (multiple periods, etc.)
        bullet = re.sub(r"\.{2,}$", "", bullet)

        # Ensure proper sentence ending (add period if missing)
        if bullet and bullet[-1] not in ".!?":
            bullet += ""  # Don't force period - let user decide

        # Enforce length limit
        if len(bullet) > MAX_BULLET_LENGTH:
            # Truncate at last complete word before limit
            truncated = bullet[:MAX_BULLET_LENGTH].rsplit(" ", 1)[0]
            bullet = truncated + "..."

        # Only include non-empty bullets
        if bullet:
            cleaned_bullets.append(bullet)

    # Step 4: Deduplicate while preserving order
    seen = set()
    deduplicated = []
    for bullet in cleaned_bullets:
        # Normalize for comparison (case-insensitive, whitespace-normalized)
        normalized = " ".join(bullet.lower().split())
        if normalized not in seen:
            seen.add(normalized)
            deduplicated.append(bullet)

    return deduplicated


def verify_grounded(bullets: list[str], detected_techs: list[str]) -> list[str]:
    """
    Verify that resume bullets are grounded in actual detected technologies.

    This is the critical hallucination guard. It ensures that any technology,
    framework, or tool mentioned in a bullet point was actually detected in
    the repository analysis. Bullets mentioning unverified technologies are
    removed to maintain resume integrity.

    Args:
        bullets: List of cleaned resume bullets
        detected_techs: List of verified technologies from stack detection
                        (canonical names from tech_taxonomy.json)

    Returns:
        Filtered list of bullets containing only verified technologies

    Example:
        >>> bullets = [
        ...     "Built FastAPI REST API with 99.9% uptime",
        ...     "Deployed to Kubernetes cluster with auto-scaling",
        ...     "Implemented React frontend with TypeScript"
        ... ]
        >>> detected = ["fastapi", "react", "typescript"]
        >>> verify_grounded(bullets, detected)
        ['Built FastAPI REST API with 99.9% uptime', 'Implemented React frontend with TypeScript']
    """
    # Normalize detected technologies for case-insensitive matching
    detected_lower = {tech.lower() for tech in detected_techs}

    # Common technology keywords that might appear in bullets
    # We'll build a comprehensive pattern from detected_techs
    verified_bullets = []

    for bullet in bullets:
        # Extract potential technology mentions from the bullet
        # Look for capitalized words and common tech patterns
        words = bullet.split()

        # Check if bullet mentions any unverified technology
        is_grounded = True
        mentioned_techs = set()

        # Pattern 1: Check for exact technology name matches (case-insensitive)
        bullet_lower = bullet.lower()
        for tech in detected_techs:
            tech_lower = tech.lower()
            # Use word boundaries to avoid partial matches
            if re.search(r'\b' + re.escape(tech_lower) + r'\b', bullet_lower):
                mentioned_techs.add(tech_lower)

        # Pattern 2: Check for common technology variations
        # (e.g., "Kubernetes" -> "k8s", "JavaScript" -> "JS")
        tech_variations = {
            "kubernetes": ["k8s", "kube"],
            "javascript": ["js"],
            "typescript": ["ts"],
            "postgresql": ["postgres", "psql"],
            "mongodb": ["mongo"],
            "docker": ["containerized", "containerization"],
        }

        for word in words:
            word_lower = word.lower().strip(",.!?;:()")

            # Check if this word is a known technology variation
            for canonical, variations in tech_variations.items():
                if word_lower in variations:
                    # Check if the canonical form is in detected techs
                    if canonical not in detected_lower:
                        # Mentioned a variation of an undetected tech
                        is_grounded = False
                        break

            # Check if word looks like a technology (capitalized, common tech names)
            # but isn't in our detected list
            if word_lower in [
                "kubernetes", "k8s", "docker", "aws", "azure", "gcp",
                "jenkins", "terraform", "ansible", "kafka", "redis",
                "elasticsearch", "graphql", "grpc", "nginx", "apache"
            ]:
                if word_lower not in detected_lower:
                    # Mentioned a specific technology that wasn't detected
                    is_grounded = False
                    break

        # If bullet mentions specific technologies, verify they were detected
        # If bullet is generic (no specific tech mentions), allow it
        if is_grounded:
            verified_bullets.append(bullet)

    return verified_bullets


def to_markdown(bullets: list[str], skills: list[dict], meta: dict) -> str:
    """
    Assemble a professional Markdown resume from bullets, skills, and metadata.

    Creates a beautifully formatted, production-ready Markdown document with:
    - Clear section headers
    - Repository profile information
    - Core skills table with proficiency scores
    - Project achievements bullet list

    Args:
        bullets: List of cleaned, verified resume bullets
        skills: List of skill dictionaries with 'technology', 'score', and 'rationale'
                (sorted by score, highest first)
        meta: Repository metadata dictionary containing:
              - repo_url: str
              - owner: str
              - repo: str
              - description: str
              - stars: int
              - primary_language: str

    Returns:
        Complete Markdown-formatted resume string with no template holes

    Example:
        >>> bullets = ["Built FastAPI REST API", "Implemented React frontend"]
        >>> skills = [
        ...     {"technology": "fastapi", "score": 85, "rationale": "FastAPI - in dependencies (+30)"},
        ...     {"technology": "react", "score": 72, "rationale": "React - in dependencies (+30)"}
        ... ]
        >>> meta = {
        ...     "repo_url": "https://github.com/user/project",
        ...     "owner": "user",
        ...     "repo": "project",
        ...     "description": "A cool project",
        ...     "stars": 42,
        ...     "primary_language": "Python"
        ... }
        >>> markdown = to_markdown(bullets, skills, meta)
        >>> "# Technical Resume" in markdown
        True
    """
    # Extract metadata with safe defaults
    repo_url = meta.get("repo_url", "")
    owner = meta.get("owner", "Unknown")
    repo = meta.get("repo", "Unknown")
    description = meta.get("description", "No description available")
    stars = meta.get("stars", 0)
    primary_language = meta.get("primary_language", "Unknown")

    # Build the Markdown document
    lines = []

    # Header
    lines.append("# Technical Resume")
    lines.append("")
    lines.append(f"**Generated from:** [{owner}/{repo}]({repo_url})")
    lines.append("")

    # Profile Section
    lines.append("## Profile")
    lines.append("")
    lines.append(f"**Repository:** {repo}")
    lines.append(f"**Owner:** {owner}")
    lines.append(f"**Description:** {description}")
    lines.append(f"**Primary Language:** {primary_language}")
    lines.append(f"**Stars:** {stars}")
    lines.append("")

    # Core Skills Section
    lines.append("## Core Skills")
    lines.append("")

    if skills:
        # Create a table with technology, score, and rationale
        lines.append("| Technology | Proficiency Score | Details |")
        lines.append("|------------|-------------------|---------|")

        for skill in skills:
            technology = skill.get("technology", "Unknown")
            score = skill.get("score", 0)
            rationale = skill.get("rationale", "No details available")

            # Capitalize technology name for display
            tech_display = technology.capitalize()

            # Create progress bar visualization (out of 100)
            bar_length = 10
            filled = int((score / 100) * bar_length)
            bar = "█" * filled + "░" * (bar_length - filled)

            lines.append(f"| **{tech_display}** | {score}/100 {bar} | {rationale} |")

        lines.append("")
    else:
        lines.append("*No skills detected*")
        lines.append("")

    # Project Achievements Section
    lines.append("## Project Achievements")
    lines.append("")

    if bullets:
        for bullet in bullets:
            # Ensure bullet doesn't already start with a marker
            bullet_text = bullet.strip()
            if not bullet_text.startswith(("-", "*", "•")):
                lines.append(f"- {bullet_text}")
            else:
                lines.append(bullet_text)
        lines.append("")
    else:
        lines.append("*No achievements listed*")
        lines.append("")

    # Footer
    lines.append("---")
    lines.append("")
    lines.append("*Generated by SkillTree.io - Transform your GitHub into a professional resume*")

    # Join all lines with newlines
    return "\n".join(lines)


def resume_strength(bullets: list[str], skills: list[dict]) -> dict[str, Any]:
    """
    Calculate resume strength score based on multiple quality factors.

    Phase 57: Resume strength scoring system that evaluates:
    - Quantified bullets (with numbers) = +10 each
    - Action verb starts = +5 each
    - Skill diversity = +20
    - Bullet length (optimal 60-120 chars) = +5 each
    - Technical depth (advanced skills) = +15

    Args:
        bullets: List of resume bullet point strings
        skills: List of skill dictionaries with 'technology' and 'score' keys

    Returns:
        Dictionary with:
        - score: int (0-100) overall resume strength
        - tips: list[str] actionable improvement suggestions

    Example:
        >>> bullets = [
        ...     "Built REST API serving 1M+ requests daily",
        ...     "Optimized queries reducing latency by 60%"
        ... ]
        >>> skills = [
        ...     {"technology": "fastapi", "score": 85},
        ...     {"technology": "postgresql", "score": 80}
        ... ]
        >>> result = resume_strength(bullets, skills)
        >>> result["score"]
        75
        >>> "quantif" in result["tips"][0].lower()
        False
    """
    score = 0
    tips = []

    # Common action verbs for resume bullets
    ACTION_VERBS = {
        "architected", "built", "created", "designed", "developed", "engineered",
        "implemented", "launched", "led", "optimized", "reduced", "improved",
        "increased", "delivered", "deployed", "migrated", "refactored", "scaled",
        "automated", "integrated", "established", "spearheaded", "collaborated",
        "managed", "coordinated", "analyzed", "researched", "investigated"
    }

    # Factor 1: Quantified bullets (with numbers)
    quantified_count = 0
    for bullet in bullets:
        # Check if bullet contains numbers (digits, percentages, etc.)
        if re.search(r'\d+', bullet):
            quantified_count += 1
            score += 10

    if quantified_count < len(bullets) * 0.5:
        tips.append("Add more quantified results (e.g., '50% faster', '1M users', '$100K saved')")

    # Factor 2: Action verb starts
    action_verb_count = 0
    for bullet in bullets:
        first_word = bullet.split()[0].lower() if bullet.split() else ""
        if first_word in ACTION_VERBS:
            action_verb_count += 1
            score += 5

    if action_verb_count < len(bullets) * 0.7:
        tips.append("Start more bullets with strong action verbs (e.g., 'Built', 'Optimized', 'Implemented')")

    # Factor 3: Skill diversity
    skill_count = len(skills)
    if skill_count >= 5:
        score += 20
    elif skill_count >= 3:
        score += 15
    elif skill_count >= 1:
        score += 10
    else:
        tips.append("Demonstrate proficiency in more technologies")

    if skill_count < 5:
        tips.append(f"Include {5 - skill_count} more skills to show technical breadth")

    # Factor 4: Bullet length optimization (60-120 chars is ideal)
    optimal_length_count = 0
    for bullet in bullets:
        length = len(bullet)
        if 60 <= length <= 120:
            optimal_length_count += 1
            score += 5
        elif length < 40:
            tips.append(f"Expand short bullets with more context and impact")
        elif length > 150:
            tips.append(f"Shorten overly long bullets for better readability")

    # Factor 5: Technical depth (high-scoring skills indicate advanced expertise)
    if skills:
        avg_skill_score = sum(s.get("score", 0) for s in skills) / len(skills)
        if avg_skill_score >= 80:
            score += 15
        elif avg_skill_score >= 60:
            score += 10
        elif avg_skill_score >= 40:
            score += 5

        if avg_skill_score < 70:
            tips.append("Deepen expertise in core technologies to demonstrate mastery")

    # Cap score at 100
    score = min(score, 100)

    # Add general tips if score is low
    if score < 50:
        tips.insert(0, "Focus on quantifying achievements and using strong action verbs")
    elif score < 70:
        tips.insert(0, "Good foundation - add more specific metrics and technical details")
    elif score >= 85:
        tips = ["Excellent resume! Minor refinements could push it to perfection"] + tips

    # Deduplicate tips while preserving order
    seen = set()
    unique_tips = []
    for tip in tips:
        if tip not in seen:
            seen.add(tip)
            unique_tips.append(tip)

    return {
        "score": score,
        "tips": unique_tips[:5]  # Limit to top 5 tips
    }
